[project]
name = "subtitle-editor"
version = "1.0.0"
description = "Blender addon: subtitle-editor"
requires-python = ">=3.10"
dependencies = [
    "faster-whisper",
    "onnxruntime>=1.24.1",
    "pysubs2>=1.8.0",
]

[tool.uv]
package = false
